#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Cache OpenWrt Build
      uses: actions/cache@v4
      with:
        path: |
          dl
          build_dir
        key: ${{ runner.os }}-openwrt-${{ hashFiles('**/.config') }}
        restore-keys: |
          ${{ runner.os }}-openwrt-

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d
        sudo apt-get update
        sudo apt-get install -y \
          build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3 python3-pip \
          unzip zlib1g-dev file wget python3-distutils rsync

    - name: Clone source code
      run: git clone --depth=1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Load custom feeds
      run: |
        [ -e "$FEEDS_CONF" ] && cp $FEEDS_CONF openwrt/feeds.conf.default
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Run DIY script part 1
      run: |
        [ -e "$DIY_P1_SH" ] && chmod +x $DIY_P1_SH && ./$DIY_P1_SH

    - name: Load custom configuration
      run: |
        [ -e "$CONFIG_FILE" ] && cp $CONFIG_FILE openwrt/.config

    - name: Run DIY script part 2
      run: |
        [ -e "$DIY_P2_SH" ] && chmod +x $DIY_P2_SH && ./$DIY_P2_SH

    - name: Download package sources
      run: |
        cd openwrt
        make defconfig
        make download -j8

    - name: Compile firmware
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s

    - name: Upload firmware to GitHub Release
      if: env.UPLOAD_RELEASE == 'true'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "openwrt/bin/targets/**/openwrt-*.bin"
        tag: OpenWrt-${{ github.run_number }}
        name: Firmware Release
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true

    - name: Upload firmware to Artifacts
      if: env.UPLOAD_FIRMWARE == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-Firmware
        path: openwrt/bin/targets

    - name: Setup SSH connection (if enabled)
      if: github.event.inputs.ssh == 'true'
      uses: P3TERX/ssh2actions@v1.0.0
